"""
DNS Builder Includer Implementations

This module contains concrete Includer implementations for different DNS software.
Each Includer handles the assembly of configuration fragments into main config files.
"""

from typing import List, Optional, Dict
import re
import logging

from ..abstractions import Includer
from ..io import DNSBPath
from ..datacls import ConfigFragment
from ..exceptions import ConfigurationError
from .. import constants

logger = logging.getLogger(__name__)


# -------------------------
#
#   BIND IMPLEMENTATIONS
#
# -------------------------

class BindIncluder(Includer):
    """
    BIND-style configuration assembler.
    """
    _tmpl = '\n# Auto Generated by DNS-Builder\ninclude "{config_line}";\n'

    def assemble(self) -> None:
        """Assemble all fragments and main configs."""
        global_config = self.main_configs.get("global")
        if not global_config:
            logger.warning("No global main config found")
            return

        # Include pending fragments into section main configs
        for section in self.get_all_sections():
            section_main = self.main_configs[section]  # Always exists due to auto-promotion
            fragments = self.get_pendings(section)

            for fragment in fragments:
                content = self._tmpl.format(config_line=fragment.dst)
                self.fs.append_text(section_main.src, content)
                logger.debug(
                    f"Included '{fragment.dst}' into section '{section}' main config"
                )

        # Include section main configs into global main config
        for section, section_main in self.main_configs.items():
            if section == "global":
                continue

            self._include_to_global(global_config, section, section_main)

    def _include_to_global(self, global_config, section: str, section_main: ConfigFragment):
        """Include a section's main config into global config."""
        section_info = self.get_section_info(section)
        include_line = self._tmpl.format(config_line=section_main.dst)

        if section_info and section_info.block_pattern and not self.is_repeatable(section):
            # Try to inject into existing block
            origin = self.fs.read_text(global_config.src)
            updated, found = self._inject_into_block(origin, section, [include_line])

            if found:
                self.fs.write_text(global_config.src, updated)
                logger.debug(f"Injected section '{section}' main config into existing block")
            else:
                # Create new block using Section template
                new_block = self._create_section_block(section, include_line, section_main.params)
                self.fs.append_text(global_config.src, new_block)
                logger.debug(f"Created new block '{section}' with main config include")
        elif section_info and self.is_repeatable(section):
            new_block = self._create_section_block(section, include_line, section_main.params)
            self.fs.append_text(global_config.src, new_block)
            logger.debug(f"Appended section '{section}' main config to global")
        else:
            # Others, no block pattern, just append
            self.fs.append_text(global_config.src, include_line)
            logger.debug(f"Appended raw include '{section}' main config to global")

    def _create_section_block(self, section: str, content: str, params: Optional[Dict[str, str]] = None) -> str:
        """
        Create a new section block using Section template.
        For non-repeatable sections (options, logging, etc.), use the Section's
        template to format the include line.
        """
        section_info = self.get_section_info(section)
        if section_info:
            # Use Section's template to format
            return f"\n# Auto Generated by DNS-Builder\n{section_info.format_content(content, **(params or {}))}\n"
        else:
            # Fallback to simple block format
            return f"\n# Auto Generated by DNS-Builder\n{section} {{\n{content}}};\n"

    def _inject_into_block(
        self,
        content: str,
        section: str,
        lines: List[str]
    ) -> tuple[str, bool]:
        """Inject include lines into an existing block using SectionInfo.block_pattern."""
        section_info = self.get_section_info(section)
        if section_info and section_info.block_pattern:
            pattern = re.compile(section_info.block_pattern, re.IGNORECASE)
        else:
            pattern = re.compile(
                rf'\b{re.escape(section)}\s*\{{',
                re.IGNORECASE
            )

        match = pattern.search(content)
        if not match:
            return content, False

        start_pos = match.end()
        brace_count = 1
        pos = start_pos

        while pos < len(content) and brace_count > 0:
            if content[pos] == '{':
                brace_count += 1
            elif content[pos] == '}':
                brace_count -= 1
            pos += 1

        if brace_count != 0:
            logger.warning(f"Unbalanced braces in block '{section}'")
            return content, False

        insert_pos = pos - 1
        insert_content = "".join(lines)

        updated = content[:insert_pos] + insert_content + content[insert_pos:]
        return updated, True


# -------------------------
#
#   UNBOUND IMPLEMENTATIONS
#
# -------------------------

class UnboundIncluder(Includer):
    """
    Unbound-style configuration assembler.

    For fragments, wrap them with the appropriate section header:
    - global fragments: include directly
    - section fragments: wrap with section template
    """
    _tmpl = '\n# Auto Generated by DNS-Builder\ninclude: "{config_line}"\n'

    def assemble(self) -> None:
        """
        Assemble all pending fragments into main configs.

        For Unbound, all sections are essentially repeatable (can appear multiple
        times), so we simply append all includes to the global main config.

        Each section fragment gets wrapped with its section header using template.
        """
        global_config = self.main_configs.get("global")
        if not global_config:
            logger.warning("No global main config found for Unbound")
            return

        for section in self.get_all_sections():
            fragments = self.get_pendings(section)
            if not fragments:
                continue

            for fragment in fragments:
                content = self._format_include_for_section(fragment)
                self.fs.append_text(global_config.src, content)
            logger.debug(f"Appended {len(fragments)} includes for section '{section}'")

        for section, section_main in self.main_configs.items():
            if section != "global":
                self.fs.append_text(global_config.src, self._format_include_for_section(section_main))

    def _format_include_for_section(self, fragment: ConfigFragment) -> str:
        """
        Format an include directive for a fragment using Section template.

        For non-global sections, use the Section's template to wrap the include.
        For global, just output the include directive.

        Args:
            fragment: ConfigFragment to format
        """
        section = fragment.section

        if section == "global":
            return self._tmpl.format(config_line=fragment.dst)
        else:
            # Use Section template to format
            include_line = self._tmpl.format(config_line=fragment.dst)
            section_info = self.get_section_info(section)

            if section_info:
                formatted = section_info.format_content(include_line)
                return f'\n# Auto-Include {section} block by DNS Builder\n{formatted}'
            else:
                # Fallback to simple format
                return (
                    f'\n# Auto-Include {section} block by DNS Builder\n'
                    f'{section}:\n{include_line}'
                )


# -------------------------
#
#   PDNS RECURSOR IMPLEMENTATIONS
#
# -------------------------

class PdnsRecursorIncluder(Includer):
    """
    PowerDNS Recursor configuration assembler.

    PowerDNS Recursor uses a simple key=value format without block structure.
    Configuration fragments are moved to an include directory and referenced
    via the include-dir directive.
    """
    _tmpl = '\n# include {config_line}'
    _write = "\n# Auto Generated by DNS Builder\ninclude-dir={include_dir}\n"

    def assemble(self) -> None:
        """
        Assemble all pending fragments for PowerDNS Recursor.

        PowerDNS Recursor uses include-dir directive to include all files
        from a directory. Fragments are moved to the include directory.
        """
        global_config = self.main_configs.get("global")
        if not global_config:
            logger.warning("No global main config found for PowerDNS Recursor")
            return

        all_fragments = []
        for section in self.get_all_sections():
            all_fragments.extend(self.get_pendings(section))

        for fragment in all_fragments:
            new_fragment = self._move_to_include_dir(fragment)
            if new_fragment:
                self._add_include_comment(global_config, new_fragment)

    def _move_to_include_dir(self, fragment: ConfigFragment) -> Optional[ConfigFragment]:
        """
        Move a fragment to the include directory.

        Args:
            fragment: ConfigFragment to move
        """
        file_name = fragment.src.__rname__
        i_dir = f"/usr/local/etc/{constants.INCLUDE_SUBDIR}"
        new_dst = DNSBPath(f"{i_dir}/{file_name}")

        global_config = self.main_configs.get("global")
        if not global_config:
            return None

        origin = self.fs.read_text(global_config.src)
        pattern = re.compile(r"^\s*include-dir\s*=\s*(.*)", re.IGNORECASE)
        _fnd_icld_dir = []

        for line in origin.splitlines():
            match = pattern.match(line)
            if match:
                _fnd_icld_dir.append(match.group(1))

        write = ""
        if not _fnd_icld_dir:
            write += self._write.format(include_dir=i_dir)
        else:
            if len(_fnd_icld_dir) > 1:
                raise ConfigurationError("Multiple include-dir found")
            if _fnd_icld_dir[0] != i_dir:
                raise ConfigurationError(
                    f"include-dir not match, expected: {i_dir}, actual: {_fnd_icld_dir[0]}"
                )

        _comment = f"{fragment.dst} -> {new_dst}"
        write += self._tmpl.format(config_line=_comment)
        self.fs.append_text(global_config.src, write)

        return ConfigFragment(
            src=fragment.src,
            dst=str(new_dst),
            dcr=fragment.dcr,
            section=fragment.section,
        )

    def _add_include_comment(self, global_config: ConfigFragment, fragment: ConfigFragment):
        """Add include comment to global config."""
        comment = f"\n# include {fragment.dst}"
        self.fs.append_text(global_config.src, comment)


class KnotResolverIncluder(Includer):
    """
    Knot Resolver configuration assembler.

    Knot Resolver uses Lua-based configuration format.
    All includes are done via dofile() function.
    """
    _tmpl = "\n-- Auto Generated by DNS Builder\ndofile('{config_line}')\n"

    def assemble(self) -> None:
        """
        Assemble all pending fragments for Knot Resolver.

        Simply append dofile() directives to the global main config.
        """
        global_config = self.main_configs.get("global")
        if not global_config:
            logger.warning("No global main config found for Knot Resolver")
            return

        all_fragments = []
        for section in self.get_all_sections():
            all_fragments.extend(self.get_pendings(section))

        for fragment in all_fragments:
            content = self._tmpl.format(config_line=fragment.dst)
            self.fs.append_text(global_config.src, content)

        logger.debug(f"Assembled {len(all_fragments)} fragments for Knot Resolver")


class KnotResolver6Includer(KnotResolverIncluder):
    """
    Knot Resolver 6 configuration assembler.

    Inherits from KnotResolverIncluder as the format is the same.
    """
    pass


# Dynamically generate __all__
from ..utils.reflection import gen_exports

__all__ = gen_exports(
    ns=globals(),
    base_path='dnsbuilder.bases.includers',
    patterns=['Includer']
)