"""
DNS Builder Data Classes Module

This module contains data classes and models for the DNSBuilder framework.

Data classes:
- BuildContext: Build context containing all build-related information
- BehaviorArtifact, VolumeArtifact, ZoneArtifact, ConfigFragment: Artifacts generated by behavior processing
- Volume: Volume mount configuration

"""

# Direct imports - no more lazy loading
from .contexts import BuildContext
from .artifacts import BehaviorArtifact, VolumeArtifact, ZoneArtifact, ConfigFragment
from .volume import Volume
from .pack import Package, PkgInstaller

__all__ = [
    # Contexts
    'BuildContext',
    # Artifacts
    'BehaviorArtifact',
    'VolumeArtifact',
    'ZoneArtifact',
    'ConfigFragment',
    # Volume
    'Volume',
    # Package
    'Package',
    'PkgInstaller',
]

