"""
DNS Builder Data Classes Module

This module contains data classes and models for the DNSBuilder framework.

Data classes:
- BuildContext: Build context containing all build-related information
- BehaviorArtifact, VolumeArtifact: Artifacts generated by behavior processing
- Volume, Pair: Volume mount configuration

"""

# Direct imports - no more lazy loading
from .contexts import BuildContext
from .artifacts import BehaviorArtifact, VolumeArtifact
from .volume import Volume, Pair

__all__ = [
    # Contexts
    'BuildContext',
    # Artifacts
    'BehaviorArtifact',
    'VolumeArtifact',
    # Volume
    'Volume',
    'Pair',
]

